### ISSUE TITLE
Build fails to access `git` executable

### ISSUE THREAD

**Issue by aochagavia** [rustls/rustls-bench-app#27]
When visiting https://bench.rustls.dev/info, this is the returned JSON:

```json
{
  "git_commit_message": "VERGEN_IDEMPOTENT_OUTPUT",
  "git_commit_sha": "VERGEN_IDEMPOTENT_OUTPUT"
}
```

I have traced the problem to the fact that the `vergen` library is unable to use the `git` executable during the build step. @cpu any clue on how to solve this, based on your ansible experience? I tried explicitly setting the `PATH` variable as follows, but it didn't change anything:

```yaml
- name: Build app
  become: true
  become_user: "{{ app_user }}"
  ansible.builtin.command: /home/{{ app_user }}/.cargo/bin/cargo build --release
  changed_when: true
  args:
    chdir: /home/{{ app_user }}/rustls-bench-app/ci-bench-runner
    # Note: omitting a 'creates' here - we want to build fresh even if the binary exists
    #       in order to pick up changes from the src git repo updating.
  environment:
    PATH: /usr/bin
```
